# -*- coding: utf-8 -*-
"""427_project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJtoATc8hp9RqbyIxay_z22MSEm1GHeE
"""

import pandas as pd

#df = pd.read_csv("merged_iot_dataset3.csv")
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Example path to your dataset (adjust it to your file's actual location)
file_path = '/content/drive/My Drive/CSE427/merged_iot_dataset4.csv'

# Load your dataset using pandas (for CSV files)
df = pd.read_csv(file_path)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format', lambda x: '%.3f' % x)


print("Dataset shape:", df.shape)
df.head()

print("\n=== Info ===")
print(df.info())

print("\n=== Columns ===")
print(df.columns.tolist())

print("\n=== Null values ===")
print(df.isnull().sum().sort_values(ascending=False).head(20))

print("\n=== Unique Labels ===")
if 'Label' in df.columns:
    print(df['Label'].value_counts())

numeric_cols = df.select_dtypes(include=np.number).columns
print("Number of numeric features:", len(numeric_cols))
print("Numeric features:", numeric_cols.tolist())


categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("\nNumber of categorical features:", len(categorical_cols))
print("Categorical features:", categorical_cols.tolist())

df.describe().T.head(20)

plt.figure(figsize=(12,6))
sns.countplot(x="Category", data=df, order=df['Category'].value_counts().index)
plt.title("Distribution of Categories")
plt.xticks(rotation=45)
plt.show()

missing = df.isnull().sum()
print("\n=== Missing Values (%): ===\n", missing)


duplicates = df.duplicated().sum()
print("\nNumber of duplicate rows:", duplicates)

df.replace([np.inf, -np.inf], np.nan, inplace=True)

df_clean = df.dropna()
df_clean = df_clean.drop_duplicates()

print("\nAfter cleaning:")
print("Shape before:", df.shape)
print("Shape after :", df_clean.shape)
print("Rows removed:", df.shape[0] - df_clean.shape[0])
df = df_clean

import seaborn as sns
import matplotlib.pyplot as plt

# Select numeric columns
numeric_cols = df.select_dtypes(include=np.number).columns

# Compute correlation matrix
corr_matrix = df[numeric_cols].corr()

# Plot heatmap
plt.figure(figsize=(20,18))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Matrix of Numeric Features")
plt.show()

# Define correlation threshold
corr_threshold = 0.9

# Create a set to store the features to remove
correlated_features = set()

# Iterate over the correlation matrix
for i in range(len(corr_matrix.columns)):
    for j in range(i):
        # If the correlation is above the threshold and the feature is not already in the removal set
        if abs(corr_matrix.iloc[i, j]) > corr_threshold:
            colname = corr_matrix.columns[i]
            correlated_features.add(colname)

# Remove correlated features from the DataFrame
df_cleaned = df.drop(columns=correlated_features)
df = df_cleaned
# Check the cleaned DataFrame
print(f"Removed features: {correlated_features}")
print(f"Remaining columns: {df_cleaned.columns}")

if 'Label' in df.columns:
    numeric_cols = df.select_dtypes(include=np.number).columns
    corr = df[numeric_cols].corrwith(df['Label'].astype('category').cat.codes)
    print("\nTop correlated features with Label:")
    print(corr.abs().sort_values(ascending=False).head(10))

    import seaborn as sns
    plt.figure(figsize=(10,6))
    top_corr = corr.abs().sort_values(ascending=False).head(15).index
    sns.heatmap(df[top_corr].corr(), annot=False, cmap="coolwarm")
    plt.title("Correlation Heatmap (Top Features)")
    plt.show()

num_cols = df.select_dtypes(include=np.number).columns[:12]

df[num_cols].hist(bins=30, figsize=(18,12))
plt.suptitle("Distribution of Numeric Features")
plt.show()

if 'Label' in df.columns:
    first_num = df.select_dtypes(include=np.number).columns[0]
    plt.figure(figsize=(8,5))
    sns.boxplot(x='Label', y=first_num, data=df)
    plt.title(f"Distribution of {first_num} by Label")
    plt.show()

# Drop non-informative categorical features
df = df.drop(columns=['Flow ID', 'Src IP', 'Dst IP', 'Timestamp', 'Category'])

# Features (X) and Target (y)
X = df.drop(columns=['Label'])   # all numeric features
y = df['Label']                  # multi-class target (0–16)

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape:", X_test.shape, y_test.shape)

from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit on train, transform both train & test
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled train shape:", X_train_scaled.shape)
print("Scaled test shape:", X_test_scaled.shape)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize the model
rf_model = RandomForestClassifier(
    n_estimators=100,     # number of trees
    random_state=42,
    n_jobs=-1             # use all CPU cores
)

# Train on scaled training data
rf_model.fit(X_train_scaled, y_train)

# Predict on test set
y_pred = rf_model.predict(X_test_scaled)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred, digits=3))

import pandas as pd
import matplotlib.pyplot as plt

feature_importances = pd.Series(rf_model.feature_importances_, index=X.columns)
top_features = feature_importances.sort_values(ascending=False).head(15)

plt.figure(figsize=(10,6))
top_features.plot(kind='barh')
plt.gca().invert_yaxis()
plt.title("Top 15 Features by Importance (Random Forest)")
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

lr_model = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=1000,
    n_jobs=-1,
    random_state=42
)

lr_model.fit(X_train_scaled, y_train)
y_pred_lr = lr_model.predict(X_test_scaled)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
print("Logistic Regression Accuracy:", round(accuracy_lr, 3))

print(classification_report(y_test, y_pred_lr, digits = 3))

# y_binary = y.copy()
# y_binary = y_binary.apply(lambda x: 0 if x == 0 else 1)

# print("Binary label distribution:")
# print(y_binary.value_counts())


# X_train, X_test, y_train, y_test = train_test_split(
#     X, y_binary, test_size=0.2, random_state=42, stratify=y_binary
# )


# rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
# rf_model.fit(X_train_scaled, y_train)
# y_pred_rf = rf_model.predict(X_test_scaled)

# print("Random Forest - Binary Classification\n")
# print(classification_report(y_test, y_pred_rf, digits=3))
# print("RF Accuracy:", round(accuracy_score(y_test, y_pred_rf), 3))


# lr_model = LogisticRegression(multi_class='ovr', solver='lbfgs', max_iter=1000, n_jobs=-1, random_state=42)
# lr_model.fit(X_train_scaled, y_train)
# y_pred_lr = lr_model.predict(X_test_scaled)

# print("Logistic Regression - Binary Classification\n")
# print(classification_report(y_test, y_pred_lr, digits=3))
# print("LR Accuracy:", round(accuracy_score(y_test, y_pred_lr), 3))

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from collections import Counter
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# === Load your dataset (replace X, y with your actual features/labels) ===
# X, y = ...

# Split into train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)

# Scale before SMOTE
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# Apply SMOTE only on training data
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)
print("After SMOTE:", Counter(y_train_res))

# === Define models ===
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

# === Train & Evaluate ===
for name, model in models.items():
    print(f"\n--- {name} ---")
    model.fit(X_train_res, y_train_res)
    y_pred = model.predict(X_test_scaled)
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)

    fig, ax = plt.subplots(figsize=(12, 10))  # control size here
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(cmap="Blues", values_format="d", ax=ax)  # pass ax explicitly
    plt.title(f"Confusion Matrix - {name}", fontsize=16)
    plt.show()

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from imblearn.over_sampling import SMOTE
from collections import Counter
import matplotlib.pyplot as plt

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# Apply SMOTE for multi-class
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)
print("After SMOTE:", Counter(y_train_res))

# Convert labels to categorical for multi-class
num_classes = 16
y_train_res_cat = tf.keras.utils.to_categorical(y_train_res, num_classes=num_classes)
y_test_cat = tf.keras.utils.to_categorical(y_test, num_classes=num_classes)

# Build multi-class DNN
def build_dnn_multiclass(input_dim, num_classes=16):
    model = Sequential([
        Dense(128, activation='relu', input_shape=(input_dim,)),
        BatchNormalization(),
        Dropout(0.3),

        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.3),

        Dense(32, activation='relu'),
        Dense(num_classes, activation='softmax')  # multi-class
    ])

    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# Build model
dnn = build_dnn_multiclass(X_train_res.shape[1], num_classes=num_classes)

# Early stopping
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train
history = dnn.fit(
    X_train_res, y_train_res_cat,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

# Predictions
y_pred_prob = dnn.predict(X_test_scaled)
y_pred = y_pred_prob.argmax(axis=1)  # choose the class with highest probability

# Metrics
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

# Plot confusion matrix
fig, ax = plt.subplots(figsize=(14, 12))
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues", values_format="d", ax=ax)
plt.title("Confusion Matrix - DNN Multi-Class", fontsize=16)
plt.show()

import matplotlib.pyplot as plt

# Extract metrics from history
train_loss = history.history['loss']
val_loss   = history.history['val_loss']
train_acc  = history.history['accuracy']
val_acc    = history.history['val_accuracy']

epochs = range(1, len(train_loss)+1)

# Plot Loss
plt.figure(figsize=(10,5))
plt.plot(epochs, train_loss, label='Train Loss', marker='o')
plt.plot(epochs, val_loss, label='Validation Loss', marker='o')
plt.title('Train vs Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

# Plot Accuracy
plt.figure(figsize=(10,5))
plt.plot(epochs, train_acc, label='Train Accuracy', marker='o')
plt.plot(epochs, val_acc, label='Validation Accuracy', marker='o')
plt.title('Train vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, Dense, Flatten, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from imblearn.over_sampling import SMOTE
from collections import Counter
import matplotlib.pyplot as plt

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# Apply SMOTE on training data
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)
print("After SMOTE:", Counter(y_train_res))

# Convert labels to categorical
num_classes = 16
y_train_res_cat = tf.keras.utils.to_categorical(y_train_res, num_classes=num_classes)
y_test_cat = tf.keras.utils.to_categorical(y_test, num_classes=num_classes)

# Reshape for Conv1D: (samples, timesteps, features=1)
X_train_cnn = X_train_res[..., None]
X_test_cnn  = X_test_scaled[..., None]

# Build 1D-CNN
model = Sequential([
    Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train_cnn.shape[1], 1)),
    BatchNormalization(),
    Dropout(0.3),

    Conv1D(32, kernel_size=3, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Flatten(),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train_cnn, y_train_res_cat,
    validation_split=0.2,
    epochs=50,
    batch_size=64,
    callbacks=[early_stop],
    verbose=1
)

# Predictions
y_pred_prob = model.predict(X_test_cnn)
y_pred = y_pred_prob.argmax(axis=1)

print(classification_report(y_test, y_pred))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(14,12))
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues", values_format="d", ax=ax)
plt.show()

import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from imblearn.over_sampling import SMOTE
from collections import Counter
import matplotlib.pyplot as plt

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)

# Apply SMOTE to training data
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
print("After SMOTE:", Counter(y_train_res))

# Create LightGBM datasets
train_data = lgb.Dataset(X_train_res, label=y_train_res)
valid_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

# LightGBM parameters for multi-class
params = {
    'objective': 'multiclass',
    'num_class': 16,
    'metric': 'multi_logloss',
    'learning_rate': 0.1,
    'num_leaves': 31,
    'verbose': -1
}

# Train with early stopping
lgb_model = lgb.train(
    params,
    train_data,
    num_boost_round=500,
    valid_sets=[train_data, valid_data],
    valid_names=['train','valid'],
    callbacks=[lgb.early_stopping(stopping_rounds=20, verbose=50)]
)

# Predictions
y_pred_prob = lgb_model.predict(X_test)
y_pred = y_pred_prob.argmax(axis=1)

# Metrics
print("LightGBM Classification Report:\n")
print(classification_report(y_test, y_pred))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(14,12))
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues", values_format="d", ax=ax)
plt.show()

# Feature importance
lgb.plot_importance(lgb_model, max_num_features=20, figsize=(10,6))
plt.show()

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Initialize XGBoost classifier
xgb_model = xgb.XGBClassifier(
    objective='multi:softprob',
    num_class=16,
    learning_rate=0.1,
    max_depth=6,
    n_estimators=500,
    use_label_encoder=False,
    eval_metric='mlogloss'
)

# Fit the model without early stopping
xgb_model.fit(
    X_train_res, y_train_res
)

# Predictions
y_pred = xgb_model.predict(X_test)

# Metrics
print("XGBoost Classification Report:\n")
print(classification_report(y_test, y_pred))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(14,12))
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues", values_format="d", ax=ax)
plt.show()

# Feature importance
xgb.plot_importance(xgb_model, max_num_features=20)
plt.show()